#!//usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
proton_2pt_distillation_L24x72 — LQCD_Master Executor v1
================================================================================

Purpose:
  Compute the proton two-point correlation function C₂(t_snk, t_src) using
  the distillation (Laplacian-Heaviside) method on the L24x72 ensemble.

Physics:
  Target observable: proton 2pt correlator (parity-projected, pp channel)
  Hadron: proton
  Ensemble: beta=6.20, mu_l=-0.2770, mu_s=-0.2400, L=24^3 x 72, a=0.1053 fm
  Method: distillation (Nev=100 eigenmodes of -nabla^2)
  Interpolator: _Cg5g4 (C gamma_5 gamma_4, DeGrand-Rossi basis)
  Momenta: Pz = -2, -3, -4, -5, -6 (z-direction, units of 2pi/L)

Expected inputs:
  - eigenvectors: eig_dir/eigvecs_t{t:03d}_{conf_id}  (binary float64)
  - perambulators: peram_dir/perams.{conf_id}.{d_src}.{t_src}  (binary float64)

Expected outputs:
  - raw contraction: (Nt, Nt, 4, 4) complex128 .npy
  - parity-projected: (Nt, Nt) float64 .npy
  - effective mass: (cosh method) .npz + .pdf plot
  - comparison report vs reference data

Example usage:
  python main.py 46000
  python main.py 46000 --Pz-list="-2,-3" --no-compare
  sbatch submit_full.sh

Generated by: LQCD_Master ExecutorAgent (deepseek-v4-pro)
Date: 2026-07-24
================================================================================
"""

import numpy as np
import os
import sys
import time
import argparse
from datetime import datetime

# ============================================================================
# Backend detection
# ============================================================================
HAS_CUPY = False
try:
    import cupy as cp
    HAS_CUPY = True
except ImportError:
    cp = None

HAS_OPT_EINSUM = False
try:
    from opt_einsum import contract as _oe_contract
    HAS_OPT_EINSUM = True
except ImportError:
    _oe_contract = None

HAS_MPL = False
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    plt = None

# ============================================================================
# Hardcoded Lattice Parameters (L24x72 ensemble)
# ============================================================================
Nt = 72
Nx = 24
Nc = 3
Nd = 4
Nev = 100
Nev1 = 100
fm2GeV = 0.1973
alttc_fm = 0.1053

mom_smear = -2
momsmear_phase = 2
Px = 0
Py = 0
element = "_Cg5g4"

# Time separation cut: only contract 2 <= deltat <= 32
DELTAT_MIN = 2
DELTAT_MAX = 32

# Paths (hardcoded per LQCD_Master Executor convention)
CONF_ID = "46000"
EIG_DIR = f"/public/group/lqcd/eigensystem/beta6.20_mu-0.2770_ms-0.2400_L24x72/{CONF_ID}/"
PERAM_U_DIR = f"/public/home/sunp/sunpeng_new_disk/mom_smear_perambulators/beta6.20_mu-0.2770_ms-0.2400_L24x72/output_dir_data/mz2_my0_mx0/{CONF_ID}/"
CORR_NUCL_DIR = f"/public/group/lqcd/donghx/2pt_Result/beta6.20_mu-0.2770_ms-0.2400_L24x72/momsmear-2z/{CONF_ID}/"

# Output directory (overridden by CLI)
OUTPUT_DIR = "./artifacts"
PLOT_DIR = "./plots"

# Momentum scan list
PZ_LIST = [-2, -3, -4, -5, -6]

# ============================================================================
# Gamma Matrices — DeGrand-Rossi Basis (NumPy, CPU)
# ============================================================================

def build_gamma_matrices():
    """Construct all 18 Dirac matrices in the DeGrand-Rossi (chiral-variant) basis."""
    z = np.zeros((4, 4), dtype=complex)
    g = {}

    g[0] = z.copy()
    for i in range(4):
        g[0][i, i] = 1.0 + 0.0j  # γ₀ = I₄

    g[1] = z.copy()
    g[1][0, 3] = 0.0 + 1.0j; g[1][1, 2] = 0.0 + 1.0j
    g[1][2, 1] = 0.0 - 1.0j; g[1][3, 0] = 0.0 - 1.0j  # γ₁ = γ_x

    g[2] = z.copy()
    g[2][0, 3] = -1.0 + 0.0j; g[2][1, 2] = 1.0 + 0.0j
    g[2][2, 1] = 1.0 + 0.0j; g[2][3, 0] = -1.0 + 0.0j  # γ₂ = γ_y

    g[3] = z.copy()
    g[3][0, 2] = 0.0 + 1.0j; g[3][1, 3] = 0.0 - 1.0j
    g[3][2, 0] = 0.0 - 1.0j; g[3][3, 1] = 0.0 + 1.0j  # γ₃ = γ_z

    g[4] = z.copy()
    g[4][0, 2] = 1.0 + 0.0j; g[4][1, 3] = 1.0 + 0.0j
    g[4][2, 0] = 1.0 + 0.0j; g[4][3, 1] = 1.0 + 0.0j  # γ₄ = γ_t

    g[5] = z.copy()
    g[5][0, 0] = 1.0 + 0.0j; g[5][1, 1] = 1.0 + 0.0j
    g[5][2, 2] = -1.0 + 0.0j; g[5][3, 3] = -1.0 + 0.0j  # γ₅

    g[6] = g[2] @ g[3];   g[7] = g[3] @ g[1];   g[8] = g[1] @ g[2]
    g[9] = g[1] @ g[4];   g[10] = g[2] @ g[4];  g[11] = g[3] @ g[4]
    g[12] = g[1] @ g[5];  g[13] = g[2] @ g[5];  g[14] = g[3] @ g[5]
    g[15] = g[4] @ g[5]
    g[16] = (g[3] @ g[1]) @ (0.5 * (g[0] + g[4]))  # P₊ projected
    g[17] = (g[3] @ g[1]) @ (0.5 * (g[0] - g[4]))  # P₋ projected
    return g


def get_contract():
    """Return the best available einsum-like contraction function."""
    if HAS_OPT_EINSUM:
        return _oe_contract
    return np.einsum


# ============================================================================
# Phase Factor and VVV Construction
# ============================================================================

def compute_phase_factor(momentum):
    """φ_P(x) = exp(-i * 2π * P·x / Nx) for all spatial points."""
    V = Nx * Nx * Nx
    phase = np.zeros(V, dtype=complex)
    idx = 0
    for z in range(Nx):
        for y in range(Nx):
            for x in range(Nx):
                phase[idx] = np.exp(
                    -np.dot(momentum, [z, y, x]) * 2.0j * np.pi / Nx
                )
                idx += 1
    return phase


def read_eigvecs_smeared(t, phase_smear, contract_fn):
    """Read eigenvectors for timeslice t and apply momentum smearing."""
    filename = f"{EIG_DIR}/eigvecs_t{t:03d}_{CONF_ID}"
    with open(filename, "rb") as f:
        file_size = os.path.getsize(filename)
        Nev_full = int(file_size / 8 / (Nx * Nx * Nx * 3 * 2))
        data = np.fromfile(f, dtype="f8").reshape(Nev_full, Nx, Nx, Nx, 3, 2)
    eigvecs = data[..., 0] + 1j * data[..., 1]                # (Nev, Nx, Nx, Nx, 3)
    eigvecs = eigvecs[:Nev1]
    eigvecs = eigvecs.reshape(Nev_full, Nx * Nx * Nx, 3)      # (Nev, V, 3)
    eigvecs_mom = contract_fn("vxa,x->vxa", eigvecs, phase_smear)
    return eigvecs_mom


def compute_vvv_for_momentum(mom, contract_fn):
    """Compute VVV baryon block for all timeslices at given momentum."""
    # Cache check
    cache_file = f"{OUTPUT_DIR}/VVV_Nev1{Nev1}_Px{Px}Py{Py}Pz{mom[0]}_conf{CONF_ID}.npy"
    if os.path.exists(cache_file):
        print(f"[CACHE] Loading VVV: {cache_file}")
        return np.load(cache_file)

    VVV_sink = np.zeros((Nt, Nev1, Nev1, Nev1), dtype=complex)
    layer_size = Nx * Nx
    phase_P = compute_phase_factor(mom)
    phase_smear = compute_phase_factor(np.array([momsmear_phase, 0, 0]))

    for t in range(Nt):
        t1 = time.perf_counter()
        eigvecs = read_eigvecs_smeared(t, phase_smear, contract_fn)
        t2 = time.perf_counter()
        print(f"[VVV] t={t:3d} read eigvecs: {t2-t1:.3f}s")

        t3 = time.perf_counter()
        for xi in range(Nx):
            start = xi * layer_size
            end = (xi + 1) * layer_size
            ps = phase_P[start:end]
            es = eigvecs[:, start:end, :]

            VVV_sink[t] += contract_fn("x,ax,bx,cx->abc", ps, es[:, :, 0], es[:, :, 1], es[:, :, 2])
            VVV_sink[t] += contract_fn("x,ax,bx,cx->abc", ps, es[:, :, 1], es[:, :, 2], es[:, :, 0])
            VVV_sink[t] += contract_fn("x,ax,bx,cx->abc", ps, es[:, :, 2], es[:, :, 0], es[:, :, 1])
            VVV_sink[t] -= contract_fn("x,ax,bx,cx->abc", ps, es[:, :, 0], es[:, :, 2], es[:, :, 1])
            VVV_sink[t] -= contract_fn("x,ax,bx,cx->abc", ps, es[:, :, 1], es[:, :, 0], es[:, :, 2])
            VVV_sink[t] -= contract_fn("x,ax,bx,cx->abc", ps, es[:, :, 2], es[:, :, 1], es[:, :, 0])
        t4 = time.perf_counter()
        print(f"[VVV] t={t:3d} contraction: {t4-t3:.3f}s")

    np.save(cache_file, VVV_sink)
    print(f"[SAVE] VVV cache: {cache_file}")
    return VVV_sink


# ============================================================================
# Perambulator I/O
# ============================================================================

def read_perambulator(t_source):
    """Read perambulator for given source timeslice."""
    parts = []
    for d_source in range(4):
        fname = f"{PERAM_U_DIR}/perams.{CONF_ID}.{d_source}.{t_source}"
        with open(fname, "rb") as f:
            parts.append(np.fromfile(f, dtype="f8"))
    peram_raw = np.concatenate(parts)

    Nev_full = int(np.sqrt(peram_raw.size / (4 * 4 * Nt * 2)))
    peram = peram_raw.reshape(4, Nt, Nev_full, 4, Nev_full, 2)
    peram = peram.transpose(1, 3, 0, 4, 2, 5)
    peram = peram[..., 0] + 1j * peram[..., 1]
    peram = peram[:, :, :, :Nev1, :Nev1]
    return peram.astype(np.complex64)


# ============================================================================
# Wick Contraction
# ============================================================================

def contract_2pt(VVV_sink, interProject1, interProject2, contract_fn):
    """Perform full Wick contraction for all (t_src, t_snk) pairs."""
    contrac_nucl_matrix = np.zeros((Nt, Nt, 4, 4), dtype=complex)

    for t_source in range(Nt):
        t_start = time.perf_counter()
        VVV_source = VVV_sink[t_source].conj()
        peram_u = read_perambulator(t_source)

        # Dirac-projected perambulator: Γ τ Γ
        CG5peram_uCG5 = contract_fn(
            "gh,thkbe,jk->tgjbe", interProject1, peram_u, interProject2
        )

        for t_sink in range(Nt):
            deltat = (t_sink - t_source + Nt) % Nt
            if DELTAT_MIN <= deltat <= DELTAT_MAX:
                contrac_nucl_matrix[t_sink, t_source] = (
                    contract_fn(
                        "abc,gjad,gjbe,ilcf,def->il",
                        VVV_sink[t_sink], peram_u[t_sink],
                        CG5peram_uCG5[t_sink], peram_u[t_sink],
                        VVV_source,
                    )
                    - contract_fn(
                        "abc,glaf,gjbe,ijcd,def->il",
                        VVV_sink[t_sink], peram_u[t_sink],
                        CG5peram_uCG5[t_sink], peram_u[t_sink],
                        VVV_source,
                    )
                )

        t_end = time.perf_counter()
        print(f"[Wick] t_source={t_source:3d} done: {t_end-t_start:.3f}s")

    return contrac_nucl_matrix


# ============================================================================
# Parity Projection & Effective Mass
# ============================================================================

def apply_parity_and_boundary(contrac_nucl_matrix, gamma):
    """Apply P_plus parity projection and boundary sign correction."""
    matrix_pplus = 0.5 * (gamma[0] + gamma[4])
    matrix_pminus = 0.5 * (gamma[0] - gamma[4])

    contrac_nucl_pp = np.einsum("li,yxil->yx", matrix_pplus, contrac_nucl_matrix)
    contrac_nucl_pm = np.einsum("li,yxil->yx", matrix_pminus, contrac_nucl_matrix)

    for t_src in range(Nt):
        for t_snk in range(Nt):
            if t_snk < t_src:
                contrac_nucl_pp[t_snk, t_src] *= -1.0
            if t_snk > t_src:
                contrac_nucl_pm[t_snk, t_src] *= -1.0

    return contrac_nucl_pp, contrac_nucl_pm


def compute_effective_mass(contrac_nucl_pp):
    """Extract 1D correlator and compute cosh effective mass."""
    C_1d = np.zeros(Nt, dtype=float)
    for dt in range(Nt):
        vals = []
        for t_src in range(Nt):
            t_snk = (t_src + dt) % Nt
            vals.append(np.real(contrac_nucl_pp[t_snk, t_src]))
        C_1d[dt] = np.mean(vals)

    C_pos = np.abs(C_1d) + 1e-30
    cosh_arg = (C_pos[2:] + C_pos[:-2]) / (2.0 * C_pos[1:-1])
    valid = cosh_arg >= 1.0
    meff_lu = np.full(Nt - 2, np.nan)
    meff_lu[valid] = np.arccosh(cosh_arg[valid])
    meff_gev = meff_lu * fm2GeV / alttc_fm

    return C_1d, meff_gev


# ============================================================================
# Comparison with Reference
# ============================================================================

def compare_with_reference(gen_data, ref_path, label):
    """Compare generated data with reference, print metrics."""
    if not os.path.exists(ref_path):
        print(f"[COMPARE] {label}: reference file not found, skipping.")
        return None
    ref_data = np.load(ref_path)
    diff = np.abs(gen_data - ref_data)
    eps = 1e-15
    rel_diff = diff / (np.abs(ref_data) + eps)
    metrics = {
        "max_abs": float(np.max(diff)),
        "mean_abs": float(np.mean(diff)),
        "max_rel": float(np.max(rel_diff)),
        "mean_rel": float(np.mean(rel_diff)),
        "frac_1e6": float(np.mean(diff < 1e-6)),
        "frac_1e10": float(np.mean(diff < 1e-10)),
    }
    print(f"[COMPARE] {label}:")
    print(f"  max|diff|={metrics['max_abs']:.4e}, mean|diff|={metrics['mean_abs']:.4e}")
    print(f"  max|diff/ref|={metrics['max_rel']:.4e}, <1e-6={metrics['frac_1e6']:.1%}")
    return metrics


# ============================================================================
# Plotting
# ============================================================================

def plot_meff(meff_gev, C_1d, Pz, save_path):
    """Plot C2pt log-scale + effective mass dual panel."""
    if not HAS_MPL:
        return
    fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))

    dt_vals = np.arange(Nt)
    axes[0].semilogy(dt_vals, np.abs(C_1d), 'o-', markersize=4, color='#4E79A7')
    axes[0].set_xlabel(r"$\Delta t~/~a$", fontsize=14)
    axes[0].set_ylabel(r"$|C_2(\Delta t)|$", fontsize=14)
    axes[0].set_title(f"C2pt (Pz={Pz})", fontsize=14)
    axes[0].grid(True, alpha=0.3, linestyle=':')

    t_meff = np.arange(1, Nt - 1)
    valid = ~np.isnan(meff_gev)
    axes[1].errorbar(t_meff[valid], meff_gev[valid],
                      fmt='o', markersize=5, mfc='none', capsize=3,
                      color='#E69F00', label='cosh meff')
    ps, pe = Nt // 4, Nt // 2
    if np.any(valid[ps:pe]):
        pm = np.mean(meff_gev[ps:pe][valid[ps:pe]])
        axes[1].axhline(y=pm, color='#D62728', linestyle='--', linewidth=1,
                         label=f'plateau ({ps}-{pe}): {pm:.3f} GeV')
        axes[1].axhspan(pm-0.05*abs(pm), pm+0.05*abs(pm),
                         alpha=0.15, color='#D62728')
    axes[1].set_xlabel(r"$t~/~a$", fontsize=14)
    axes[1].set_ylabel(r"$m_{\mathrm{eff}}~/~\mathrm{GeV}$", fontsize=14)
    axes[1].set_title(f"Effective Mass (Pz={Pz})", fontsize=14)
    axes[1].grid(True, alpha=0.3, linestyle=':')
    axes[1].legend(fontsize=11)

    plt.tight_layout()
    fig.savefig(save_path, bbox_inches='tight')
    plt.close(fig)
    print(f"[PLOT] {save_path}")


def plot_comparison(gen, ref, Pz, label, save_path):
    """Scatter + histogram comparison plot."""
    if not HAS_MPL:
        return
    gen_flat = np.real(gen).ravel()
    ref_flat = np.real(ref).ravel()
    diff_flat = np.abs(gen - ref).ravel()
    nonzero = diff_flat > 0
    diff_log = np.log10(diff_flat[nonzero]) if np.any(nonzero) else np.array([-16])

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    axes[0].scatter(ref_flat, gen_flat, s=1, alpha=0.3)
    lims = [np.min(ref_flat), np.max(ref_flat)]
    axes[0].plot(lims, lims, 'r--', linewidth=1, label='y=x')
    axes[0].set_xlabel(f"Re(Ref) — {label}")
    axes[0].set_ylabel(f"Re(Gen) — {label}")
    axes[0].legend(fontsize=9)
    axes[0].grid(True, alpha=0.3)

    axes[1].hist(diff_log, bins=50, color='C1', alpha=0.7, edgecolor='k')
    axes[1].set_xlabel("log10(|Gen - Ref|)")
    axes[1].set_ylabel("Count")
    axes[1].axvline(x=-6, color='r', linestyle='--', linewidth=1, label='1e-6')
    axes[1].axvline(x=-10, color='g', linestyle='--', linewidth=1, label='1e-10')
    axes[1].legend(fontsize=9)

    plt.tight_layout()
    fig.savefig(save_path, bbox_inches='tight')
    plt.close(fig)
    print(f"[PLOT] {save_path}")


# ============================================================================
# Main Workflow
# ============================================================================

def main():
    global CONF_ID, EIG_DIR, PERAM_U_DIR, CORR_NUCL_DIR, OUTPUT_DIR, PLOT_DIR
    global PZ_LIST

    parser = argparse.ArgumentParser(description="Proton 2pt distillation (LQCD_Master Executor v1)")
    parser.add_argument("conf_id", type=str, nargs="?", default="46000",
                        help="Configuration ID")
    parser.add_argument("--Pz-list", type=str, default="-2,-3,-4,-5,-6",
                        help="Comma-separated momentum list")
    parser.add_argument("--eig-dir", type=str, default="",
                        help="Override eigenvector directory")
    parser.add_argument("--peram-dir", type=str, default="",
                        help="Override perambulator directory")
    parser.add_argument("--ref-dir", type=str, default="",
                        help="Override reference data directory")
    parser.add_argument("--output-dir", type=str, default="./artifacts",
                        help="Output directory for generated data")
    parser.add_argument("--no-compare", action="store_true",
                        help="Skip comparison with reference data")
    parser.add_argument("--no-plot", action="store_true",
                        help="Skip plot generation")
    args = parser.parse_args()

    # Override globals from CLI
    CONF_ID = args.conf_id
    if args.eig_dir: EIG_DIR = args.eig_dir.format(conf_id=CONF_ID)
    else: EIG_DIR = EIG_DIR.replace("46000", CONF_ID)
    if args.peram_dir: PERAM_U_DIR = args.peram_dir.format(conf_id=CONF_ID)
    else: PERAM_U_DIR = PERAM_U_DIR.replace("46000", CONF_ID)
    if args.ref_dir: CORR_NUCL_DIR = args.ref_dir.format(conf_id=CONF_ID)
    else: CORR_NUCL_DIR = CORR_NUCL_DIR.replace("46000", CONF_ID)

    OUTPUT_DIR = args.output_dir
    PLOT_DIR = os.path.join(OUTPUT_DIR, "plots")
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(PLOT_DIR, exist_ok=True)

    PZ_LIST = [int(p) for p in args.Pz_list.split(",")]

    print(f"{'='*60}")
    print(f"  Proton 2pt Distillation — LQCD_Master Executor v1")
    print(f"{'='*60}")
    print(f"  conf_id = {CONF_ID}")
    print(f"  Nt={Nt}, Nx={Nx}, Nev={Nev}, Nev1={Nev1}")
    print(f"  Pz_list = {PZ_LIST}")
    print(f"  element = {element}")
    print(f"  eig_dir = {EIG_DIR}")
    print(f"  peram_u_dir = {PERAM_U_DIR}")
    print(f"  ref_dir = {CORR_NUCL_DIR}")
    print(f"  output = {OUTPUT_DIR}")
    print(f"  plots  = {PLOT_DIR}")
    print(f"{'='*60}\n")

    # Initialize gamma matrices and contraction function
    gamma = build_gamma_matrices()
    contract_fn = get_contract()

    # Interpolator matrices: _Cg5g4 = gamma(7) @ gamma(4) = gamma_3 gamma_1 gamma_4
    interProject1 = gamma[7] @ gamma[4]
    interProject2 = gamma[7] @ gamma[4]

    # Precompute momentum smearing phase factor
    phase_smear = compute_phase_factor(np.array([momsmear_phase, 0, 0]))
    print(f"[INIT] phase_smear shape: {phase_smear.shape}")

    # Check perambulator availability
    test_peram = f"{PERAM_U_DIR}/perams.{CONF_ID}.0.0"
    if not os.path.exists(test_peram):
        print(f"[FATAL] Perambulator file not found: {test_peram}")
        print(f"        Check --peram-dir path or conf_id.")
        sys.exit(1)

    t_total_start = time.perf_counter()
    all_metrics = {}

    # ── Main loop: each Pz ──────────────────────────────────
    for Pz in PZ_LIST:
        mom = np.array([Pz, Py, Px])
        print(f"\n{'─'*50}")
        print(f"  Pz = {Pz}")
        print(f"{'─'*50}")

        # ── VVV ──
        t_vvv = time.perf_counter()
        VVV_sink = compute_vvv_for_momentum(mom, contract_fn)
        print(f"[TIME] VVV: {time.perf_counter()-t_vvv:.1f}s")

        # ── Wick contraction ──
        t_wick = time.perf_counter()
        contrac = contract_2pt(VVV_sink, interProject1, interProject2, contract_fn)
        print(f"[TIME] Wick: {time.perf_counter()-t_wick:.1f}s")

        # ── Save raw contraction ──
        raw_fn = f"twopt_slice_pp_Px{Px}Py{Py}Pz{Pz}_eginphase{mom_smear}{element}_contract_conf{CONF_ID}.npy"
        np.save(f"{OUTPUT_DIR}/{raw_fn}", contrac)
        print(f"[SAVE] {OUTPUT_DIR}/{raw_fn}")

        # ── Parity + boundary ──
        contrac_pp, contrac_pm = apply_parity_and_boundary(contrac, gamma)
        pp_fn = f"twopt_slice_pp_Px{Px}Py{Py}Pz{Pz}_eginphase{mom_smear}{element}_nopol_ss_conf{CONF_ID}.npy"
        np.save(f"{OUTPUT_DIR}/{pp_fn}", contrac_pp)
        print(f"[SAVE] {OUTPUT_DIR}/{pp_fn}")

        # ── Effective mass ──
        C_1d, meff_gev = compute_effective_mass(contrac_pp)
        np.savez(f"{OUTPUT_DIR}/meff_Pz{Pz}_conf{CONF_ID}.npz",
                  meff_gev=meff_gev, C2pt_1d=C_1d)
        print(f"[SAVE] meff_Pz{Pz}_conf{CONF_ID}.npz")
        for t in range(1, min(Nt - 1, 12)):
            print(f"  t={t:3d}: meff = {meff_gev[t-1]:.4f} GeV")

        # ── Compare ──
        if not args.no_compare:
            ref_raw = f"{CORR_NUCL_DIR}/{raw_fn}"
            ref_pp  = f"{CORR_NUCL_DIR}/{pp_fn}"
            metrics_r = compare_with_reference(contrac, ref_raw, f"Raw Pz={Pz}")
            metrics_p = compare_with_reference(contrac_pp, ref_pp, f"PP Pz={Pz}")
            all_metrics[f"Pz={Pz}"] = {"raw": metrics_r, "pp": metrics_p}
            if metrics_r and not args.no_plot:
                ref = np.load(ref_raw)
                plot_comparison(contrac, ref, Pz, f"C2(t_snk,t_src) Pz={Pz}",
                                 f"{PLOT_DIR}/raw_Pz{Pz}_comparison.pdf")
            if metrics_p and not args.no_plot:
                ref = np.load(ref_pp)
                plot_comparison(contrac_pp, ref, Pz, f"C2_pp Pz={Pz}",
                                 f"{PLOT_DIR}/pp_Pz{Pz}_comparison.pdf")

        # ── Plot ──
        if not args.no_plot:
            plot_meff(meff_gev, C_1d, Pz,
                       f"{PLOT_DIR}/meff_Pz{Pz}_{element}_conf{CONF_ID}.pdf")

    # ── Summary ──
    t_total = time.perf_counter() - t_total_start
    print(f"\n{'═'*60}")
    print(f"  JOB: ran successfully")
    print(f"  Total time: {t_total:.1f}s ({t_total/3600:.1f}h)")
    print(f"  Output: {OUTPUT_DIR}")
    print(f"{'═'*60}")

    if all_metrics:
        print(f"\n  Comparison Summary:")
        for k, v in all_metrics.items():
            if v["pp"]:
                print(f"  {k}: max|d|={v['pp']['max_abs']:.2e}, "
                      f"<1e-6={v['pp']['frac_1e6']:.1%}")


if __name__ == "__main__":
    main()
