#!/bin/bash
# ============================================================================
# Proton 2pt Distillation — Test Submission
# Generated by: LQCD_Master ExecutorAgent v1
# Date: 2026-07-24
# ============================================================================
#SBATCH -J proton_2pt_test
#SBATCH -p cpu6248R,cpueicc,i72c512g
#SBATCH --output=/public/home/zhangxin/lattice-pdf/agent/snsc/logs/test_%j.out
#SBATCH --error=/public/home/zhangxin/lattice-pdf/agent/snsc/logs/test_%j.err
#SBATCH --nodes=1
#SBATCH -n 1
#SBATCH --time=00:30:00
#SBATCH --ntasks-per-node=1
#SBATCH --chdir=/public/home/zhangxin/lattice-pdf/agent/snsc

set -euo pipefail

source /public/home/zhangxin/miniconda3/etc/profile.d/conda.sh && conda activate zhangxin-snsc

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

echo "=== Test Job Started: $(date) ==="
echo "Node: $(hostname)"
echo "Conf: 46000"
echo "Pz: -2 (single momentum, test mode)"

python -u executor_v1/main.py 46000 --Pz-list="-2" \
    --output-dir=artifacts/test 2>&1

echo "=== Test Job Finished: $(date) ==="
