#!/bin/bash
# ============================================================================
# Proton 2pt Distillation — Full Production Submission
# Generated by: LQCD_Master ExecutorAgent v1
# Date: 2026-07-24
# ============================================================================
#SBATCH -J proton_2pt_full
#SBATCH -p cpu6248R,cpueicc,i72c512g
#SBATCH --output=/public/home/zhangxin/lattice-pdf/agent/snsc/logs/full_%j.out
#SBATCH --error=/public/home/zhangxin/lattice-pdf/agent/snsc/logs/full_%j.err
#SBATCH --nodes=1
#SBATCH -n 1
#SBATCH --time=48:00:00
#SBATCH --ntasks-per-node=1
#SBATCH --chdir=/public/home/zhangxin/lattice-pdf/agent/snsc

set -euo pipefail

source /public/home/zhangxin/miniconda3/etc/profile.d/conda.sh && conda activate zhangxin-snsc

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_DIR="runs/${TIMESTAMP}"
mkdir -p "${LOG_DIR}" "${LOG_DIR}/plots"

echo "=== Full Job Started: $(date) ==="
echo "Node: $(hostname)"
echo "Log:  ${LOG_DIR}"

python -u executor_v1/main.py 46000 \
    --Pz-list="-2,-3,-4,-5,-6" \
    --output-dir="${LOG_DIR}" 2>&1 | tee "${LOG_DIR}/run.log"

echo "=== Full Job Finished: $(date) ==="
echo "Output: ${LOG_DIR}"
ls -lh "${LOG_DIR}/"
