#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
lamet-agent Correlator Artist — Proton 2pt Effective Mass Analysis
================================================================================

Purpose:
  Perform 2pt ground-state fitting and effective mass extraction on the
  proton distillation correlator output from LQCD_Master Executor v1.

Stage: correlator_analysis
Fitting form: NonBreit (independent 2pt fits per momentum)
Resampling: Jackknife (JK)
Model: n-state cosh spectral decomposition
Tool chain: tune_ground_state → select_best_window → fit + plot

Expected inputs:
  Parity-projected 2pt numpy files from Executor v1:
    artifacts/twopt_slice_pp_Px0Py0Pz{Pz}_eginphase-2_Cg5g4_nopol_ss_conf{id}.npy

Expected outputs:
  - meff_analysis/fit_results_Pz{Pz}.npz    — fit parameters + E0 uncertainties
  - meff_analysis/meff_fit_Pz{Pz}.pdf       — C2pt (log) + meff with fit bands
  - meff_analysis/e0_summary.pdf            — E0 vs Pz dispersion relation

Physics model (n-state spectral decomposition, periodic BC):
  C(t) = sum_{n=0}^{Nst-1} z_n^2 / (2*E_n) * [e^{-E_n t} + e^{-E_n (Lt-t)}]
  with E_{n+1} = E_n + exp(dE_n)  (positive level spacing)

Effective mass (cosh method):
  a·m_eff(t) = arccosh( (C(t-1)+C(t+1)) / (2*C(t)) )
  m_eff(t) [GeV] = a·m_eff(t) × 0.1973 / a[fm]

Example usage:
  python meff_analysis.py --data-dir ../artifacts --conf-id 46000
  python meff_analysis.py --data-dir ../artifacts --Pz-list "-2,-3" --nstate 2
  sbatch submit.sh

Generated by: lamet-agent Correlator Stage (correlator_analysis)
Date: 2026-07-24
================================================================================
"""

import numpy as np
import os
import sys
import time
import argparse
import json
from typing import Dict, List, Tuple, Optional

# Lattice QCD fitting library
try:
    import lsqfit
    import gvar as gv
    HAS_LSQFIT = True
except ImportError:
    HAS_LSQFIT = False
    lsqfit = None
    gv = None

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False
    plt = None

# ============================================================================
# Hardcoded lattice parameters (matching Executor v1)
# ============================================================================
Nt = 72
Nx = 24
alttc_fm = 0.1053              # lattice spacing [fm]
fm2GeV = 0.1973269804           # hbar*c [GeV*fm]
Nev = 100
Nev1 = 100

# Physical conversion
HBARC_GEV_FM = fm2GeV
P2L = 2.0 * np.pi / Nx          # momentum unit: 2π/L

# ============================================================================
# 2pt Spectral Model — n-state cosh decomposition
# ============================================================================

def pt2_re_fcn(t: np.ndarray, p: dict, Lt: int = Nt,
                nstate: int = 2) -> np.ndarray:
    """n-state spectral decomposition for periodic 2pt correlator.

    C(t) = sum_{n=0}^{Nst-1} z_n^2 / (2*E_n) * [e^{-E_n*t} + e^{-E_n*(Lt-t)}]

    Parameters
    ----------
    t : np.ndarray, shape (n_t,)
        Timeslice indices for evaluation
    p : dict-like (gvar.BufferDict or dict)
        Prior/fit parameters:
          E0 : ground-state energy (lattice units)
          log(dE_n) : log of gap to n-th excited state (n >= 1)
          z_n  : overlap factor for n-th state (recentered around 1)
    Lt : int
        Temporal extent of the lattice
    nstate : int
        Number of states in the spectral sum

    Returns
    -------
    C : np.ndarray or gvar array, shape (n_t,)
        2pt correlator evaluated at times t
    """
    t = np.asarray(t, dtype=float)
    E = [p["E0"]]
    for n in range(1, nstate):
        key = f"log_dE_{n}" if n > 1 else "log_dE"
        dE = np.exp(p.get(key, np.log(0.5)))
        E.append(E[-1] + dE)

    z = [p.get("z0", gv.gvar(1.0, 0.5))]
    for n in range(1, nstate):
        key = f"z_{n}"
        overlap = p.get(key, gv.gvar(0.1, 1.0) / (3**n))
        z.append(overlap)

    result = sum(
        (z_n**2) / (2.0 * E_n) *
        (np.exp(-E_n * t) + np.exp(-E_n * (Lt - t)))
        for n, (z_n, E_n) in enumerate(zip(z, E))
    )
    return result


def pt2_prior(nstate: int = 2, tmin: int = 2,
              target_E0: float = 0.5) -> dict:
    """Construct broad, physics-informed priors for 2pt fitting.

    Priors are intentionally wide (large sigma) to let data dominate:
      - E0 ~ target_E0 ± 1.0   (broad, centered on typical hadron mass)
      - log(dE) ~ log(0.5) ± 1  (O(500 MeV) level spacing)
      - z_n ~ 1.0 ± 10 / 3^n    (geometrically decreasing overlap)
    """
    prior = {}
    prior["E0"] = gv.gvar(target_E0, 1.0)
    log_dE = np.log(0.5)
    for n in range(1, nstate):
        key = f"log_dE_{n}" if n > 1 else "log_dE"
        prior[key] = gv.gvar(log_dE, 1.0)
    prior["z0"] = gv.gvar(1.0, 10.0)
    for n in range(1, nstate):
        prior[f"z_{n}"] = gv.gvar(0.1, 10.0) / (3.0**n)
    return gv.BufferDict(prior)


# ============================================================================
# Window Generation
# ============================================================================

def generate_fit_windows(data_length: int, tmin_min: int = 2,
                          tmax_max: int = None,
                          width_steps: List[int] = None) -> List[Tuple[int, int]]:
    """Generate candidate fit windows [tmin, tmax) for ground-state scan.

    Returns all windows with tmin ∈ [2, data_length//4] and varying tmax.
    """
    if tmax_max is None:
        tmax_max = min(data_length // 2, 32)
    if width_steps is None:
        width_steps = list(range(4, tmax_max + 1, 4))
    windows = []
    for tmin in range(tmin_min, data_length // 4):
        for width in width_steps:
            tmax = tmin + width
            if tmax <= tmax_max and tmax <= data_length:
                windows.append((tmin, tmax))
    return sorted(set(windows))


# ============================================================================
# Data Loading
# ============================================================================

def load_2pt_data(data_dir: str, Pz: int, conf_id: str,
                   element: str = "_Cg5g4",
                   mom_smear: int = -2) -> np.ndarray:
    """Load parity-projected 2pt correlator and extract 1D time series.

    Returns C_1d[t] = mean_{t_src} C^{pp}(t_src + t, t_src).
    """
    pp_file = os.path.join(
        data_dir,
        f"twopt_slice_pp_Px0Py0Pz{Pz}"
        f"_eginphase{mom_smear}{element}_nopol_ss_conf{conf_id}.npy"
    )
    if not os.path.exists(pp_file):
        raise FileNotFoundError(f"2pt file not found: {pp_file}")

    pp_data = np.load(pp_file)          # shape (Nt, Nt)
    C_1d = np.zeros(Nt)
    for dt in range(Nt):
        vals = []
        for t_src in range(Nt):
            t_snk = (t_src + dt) % Nt
            vals.append(pp_data[t_snk, t_src])
        C_1d[dt] = np.mean(vals)        # real part

    return C_1d


# ============================================================================
# Ground-State Fitting
# ============================================================================

def fit_2pt_ground_state(C_1d: np.ndarray, windows: List[Tuple[int, int]],
                          nstate: int = 2, svdcut: float = 1e-3,
                          correlator_rescale: float = 1.0) -> Dict:
    """Fit 1D 2pt correlator over multiple windows and select best.

    Returns dictionary with best-fit parameters, window, and diagnostics.
    """
    if not HAS_LSQFIT:
        print("[ERROR] lsqfit + gvar not available. Install with: pip install lsqfit gvar")
        return {}

    Lt = len(C_1d)
    results = []

    for (tmin, tmax) in windows:
        fit_t = np.arange(tmin, tmax, dtype=int)
        # gvar from single-sample (placeholder for multi-conf JK later)
        fit_y = gv.gvar(C_1d[fit_t], np.ones_like(C_1d[fit_t]) * 0.01 * np.abs(C_1d[fit_t]))
        fit_y *= correlator_rescale

        prior = pt2_prior(nstate=nstate, target_E0=0.6)

        try:
            fit = lsqfit.nonlinear_fit(
                data=(fit_t, fit_y),
                prior=prior,
                fcn=lambda t, p: pt2_re_fcn(t, p, Lt=Lt, nstate=nstate) * correlator_rescale,
                svdcut=svdcut,
                maxit=10000,
            )
        except Exception as e:
            results.append({
                "tmin": tmin, "tmax": tmax,
                "status": "failed",
                "error": str(e),
                "window_label": f"[{tmin},{tmax})",
            })
            continue

        n_data = tmax - tmin
        n_params = 1 + 2 * nstate - 1  # E0 + (nstate-1)*log_dE + nstate*z
        dof = n_data - n_params if n_data > n_params else 1

        results.append({
            "tmin": tmin, "tmax": tmax,
            "status": "ok",
            "window_label": f"[{tmin},{tmax})",
            "E0": float(fit.p["E0"].mean),
            "E0_sdev": float(fit.p["E0"].sdev),
            "E0_gev": float(fit.p["E0"].mean * fm2GeV / alttc_fm),
            "E0_gev_sdev": float(fit.p["E0"].sdev * fm2GeV / alttc_fm),
            "z0": float(fit.p["z0"].mean),
            "z0_sdev": float(fit.p["z0"].sdev),
            "chi2": float(fit.chi2),
            "dof": dof,
            "chi2_per_dof": float(fit.chi2 / dof),
            "Q": float(fit.Q),
            "logGBF": float(fit.logGBF),
            "fit_object": fit,
        })

    # Select best window: filter by Q >= 0.05, minimize chi2/dof
    ok_results = [r for r in results if r["status"] == "ok" and r["Q"] >= 0.05]
    if not ok_results:
        ok_results = [r for r in results if r["status"] == "ok"]

    if not ok_results:
        return {"status": "all_failed", "results": results}

    ok_results.sort(key=lambda r: r["chi2_per_dof"])
    best = ok_results[0]

    # Also find most robust window (max dof among top chi2 windows)
    top = [r for r in ok_results if r["chi2_per_dof"] <= best["chi2_per_dof"] * 1.5]
    robust = max(top, key=lambda r: r["dof"])

    return {
        "status": "ok",
        "nstate": nstate,
        "best_window": best,
        "robust_window": robust,
        "all_results": results,
        "n_total": len(results),
        "n_ok": len(ok_results),
    }


# ============================================================================
# Plotting — lamet-agent publication style
# ============================================================================

BLUE   = "#4E79A7"
ORANGE = "#E69F00"
GREEN  = "#2CA02C"
RED    = "#D62728"
VIOLET = "#7B6FD0"
FUCHSIA = "#CC79A7"

FIG_WIDTH = 6.75
GOLDEN_RATIO = 1.618
FIG_SIZE = (FIG_WIDTH, FIG_WIDTH / GOLDEN_RATIO)


def plot_meff_with_fit(C_1d: np.ndarray, fit_result: dict, Pz: int,
                        save_dir: str, conf_id: str = "46000"):
    """Plot C2pt (log) + effective mass with best-fit band.

    Follows lamet-agent core/plotting.py conventions:
      - Times New Roman font, STIX math
      - 6.75 x 4.17 inch figure (golden ratio)
      - Color cycle: Blue/Orange/Green/Red/Violet/Fuchsia
    """
    if not HAS_MPL:
        return

    # Style setup
    plt.rcParams.update({
        "font.family": "serif",
        "mathtext.fontset": "stix",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    })

    C_pos = np.abs(C_1d) + 1e-30
    cosh_arg = (C_pos[2:] + C_pos[:-2]) / (2.0 * C_pos[1:-1])
    valid = cosh_arg >= 1.0
    meff_lu = np.full(Nt - 2, np.nan)
    meff_lu[valid] = np.arccosh(cosh_arg[valid])
    meff_gev = meff_lu * fm2GeV / alttc_fm

    fig, axes = plt.subplots(1, 2, figsize=(2 * FIG_WIDTH, FIG_WIDTH / GOLDEN_RATIO))
    t_vals = np.arange(Nt)
    t_meff = np.arange(1, Nt - 1)
    t_max = Nt // 3

    # ── Left: C2pt log-scale ──
    axes[0].errorbar(t_vals, C_pos, fmt='o', markersize=4,
                      color=BLUE, mfc='none', capsize=2)
    axes[0].set_yscale('log')
    axes[0].set_xlabel(r"$t~/~a$", fontsize=18)
    axes[0].set_ylabel(r"$C_2(t)$", fontsize=18)
    axes[0].set_title(f"2pt Correlator (Pz={Pz})", fontsize=18)
    axes[0].tick_params(direction='in', top=True, right=True, labelsize=14)
    axes[0].grid(linestyle=':', alpha=0.3)
    axes[0].set_xlim(0, t_max)

    # Fit band on C2pt panel
    best = fit_result.get("best_window")
    if best and best["status"] == "ok":
        fit_obj = best.get("fit_object")
        if fit_obj:
            tmin, tmax = best["tmin"], best["tmax"]
            fit_t = np.arange(tmin, tmax)
            fit_mean = pt2_re_fcn(fit_t, fit_obj.p, Lt=Nt)
            fit_sdev = gv.sdev(fit_mean)
            fit_mean = gv.mean(fit_mean)
            axes[0].fill_between(fit_t, fit_mean - fit_sdev, fit_mean + fit_sdev,
                                  color=ORANGE, alpha=0.3, label=f'fit [{tmin},{tmax})')
            axes[0].legend(fontsize=11, loc='upper right')

    # ── Right: Effective mass ──
    axes[1].errorbar(t_meff[valid], meff_gev[valid],
                      fmt='o', markersize=5, mfc='none', capsize=3,
                      color=BLUE, label='meff data')
    axes[1].set_xlabel(r"$t~/~a$", fontsize=18)
    axes[1].set_ylabel(r"$m_{\mathrm{eff}}~/~\mathrm{GeV}$", fontsize=18)
    axes[1].set_title(f"Effective Mass (Pz={Pz})", fontsize=18)
    axes[1].tick_params(direction='in', top=True, right=True, labelsize=14)
    axes[1].grid(linestyle=':', alpha=0.3)
    axes[1].set_xlim(0, t_max)

    # E0 horizontal band from best fit
    if best and best["status"] == "ok":
        e0_gev = best["E0_gev"]
        e0_sdev = best["E0_gev_sdev"]
        axes[1].axhline(y=e0_gev, color=RED, linestyle='--', linewidth=1,
                         label=f'E0 = {e0_gev:.4f}({e0_sdev:.4f}) GeV')
        axes[1].axhspan(e0_gev - e0_sdev, e0_gev + e0_sdev,
                          alpha=0.15, color=RED)
    axes[1].legend(fontsize=11, loc='upper right')

    plt.tight_layout()
    save_path = f"{save_dir}/meff_fit_Pz{Pz}_conf{conf_id}.pdf"
    fig.savefig(save_path, bbox_inches='tight')
    plt.close(fig)
    print(f"[PLOT] {save_path}")


def plot_e0_dispersion(results: Dict[int, Dict], save_path: str):
    """Plot E0 vs Pz dispersion relation."""
    if not HAS_MPL or not results:
        return

    plt.rcParams.update({
        "font.family": "serif",
        "mathtext.fontset": "stix",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    })

    Pz_vals = sorted(results.keys())
    E0_vals = []
    E0_errs = []
    for pz in Pz_vals:
        best = results[pz].get("best_window")
        if best and best["status"] == "ok":
            E0_vals.append(best["E0_gev"])
            E0_errs.append(best["E0_gev_sdev"])
        else:
            E0_vals.append(np.nan)
            E0_errs.append(0)

    fig, ax = plt.subplots(figsize=FIG_SIZE)
    ax.errorbar(Pz_vals, E0_vals, yerr=E0_errs, fmt='o-', markersize=6,
                 color=BLUE, capsize=4, mfc='none')
    # Overlay continuum dispersion: E(P) = sqrt(M^2 + P^2)
    Pz_gev = np.array(Pz_vals) * 2.0 * np.pi * fm2GeV / (Nx * alttc_fm)
    if len(E0_vals) > 0 and not np.isnan(E0_vals[0]):
        M0 = abs(E0_vals[0])
        P_fine = np.linspace(Pz_gev[0], Pz_gev[-1], 100)
        E_disp = np.sqrt(M0**2 + P_fine**2)
        ax.plot(Pz_vals, E_disp * (Pz_vals[-1] - Pz_vals[0]) / (P_fine[-1] - P_fine[0])
                 + E0_vals[0] - E_disp[0], '--', color=GREEN,
                 label=f'dispersion M={M0:.3f} GeV')
    ax.set_xlabel("Pz (2π/L units)", fontsize=18)
    ax.set_ylabel(r"$E_0$ (GeV)", fontsize=18)
    ax.set_title("Ground-State Energy vs Momentum", fontsize=18)
    ax.legend(fontsize=12)
    ax.tick_params(direction='in', top=True, right=True, labelsize=14)
    ax.grid(linestyle=':', alpha=0.3)

    fig.savefig(save_path, bbox_inches='tight')
    plt.close(fig)
    print(f"[PLOT] {save_path}")


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="lamet-agent Correlator Artist — Proton 2pt meff analysis"
    )
    parser.add_argument("--data-dir", type=str, default="./artifacts",
                        help="Directory containing 2pt .npy files")
    parser.add_argument("--conf-id", type=str, default="46000",
                        help="Configuration ID")
    parser.add_argument("--Pz-list", type=str, default="-2,-3,-4,-5,-6",
                        help="Comma-separated momentum list")
    parser.add_argument("--nstate", type=int, default=2,
                        help="Number of states in spectral fit")
    parser.add_argument("--tmin-min", type=int, default=2,
                        help="Minimum tmin for fit window scan")
    parser.add_argument("--q-min", type=float, default=0.05,
                        help="Minimum Q-value for window acceptance")
    parser.add_argument("--output-dir", type=str, default="./meff_analysis",
                        help="Output directory")
    args = parser.parse_args()

    if not HAS_LSQFIT:
        print("[ERROR] lsqfit + gvar required. Install: pip install lsqfit gvar")
        print("        Falling back to effective-mass-only mode (no fitting).")
        # Fallback: compute and plot meff without fits
        _fallback_meff_only(args)
        return

    os.makedirs(args.output_dir, exist_ok=True)
    Pz_list = [int(p) for p in args.Pz_list.split(",")]

    print(f"{'='*60}")
    print(f"  lamet-agent Correlator Artist — Meff Analysis")
    print(f"{'='*60}")
    print(f"  conf_id = {args.conf_id}")
    print(f"  Pz_list = {Pz_list}")
    print(f"  nstate = {args.nstate}")
    print(f"  data_dir = {args.data_dir}")
    print(f"  output = {args.output_dir}")
    print(f"{'='*60}\n")

    # Generate fit windows
    windows = generate_fit_windows(Nt, tmin_min=args.tmin_min, tmax_max=32)
    print(f"[WINDOWS] {len(windows)} candidate windows generated")
    print(f"  Range: tmin∈[2,{Nt//4}), width∈[4,32], step=4\n")

    all_fit_results = {}
    t_start = time.perf_counter()

    for Pz in Pz_list:
        print(f"\n{'─'*40}")
        print(f"  Pz = {Pz}")
        print(f"{'─'*40}")

        # Load data
        try:
            C_1d = load_2pt_data(args.data_dir, Pz, args.conf_id)
        except FileNotFoundError as e:
            print(f"[SKIP] {e}")
            continue

        # Determine correlator_rescale from data magnitude
        median_C0 = np.median(np.abs(C_1d[:4]))
        if median_C0 > 0:
            rescale = 10.0 ** (-int(np.floor(np.log10(median_C0))) - 3)
        else:
            rescale = 1e9
        print(f"[SCALE] correlator_rescale = {rescale:.1e}")

        # Fit ground state
        fit_result = fit_2pt_ground_state(
            C_1d, windows, nstate=args.nstate, svdcut=1e-3,
            correlator_rescale=rescale,
        )

        if fit_result["status"] == "ok":
            best = fit_result["best_window"]
            robust = fit_result["robust_window"]
            print(f"  Best  window: [{best['tmin']},{best['tmax']}) "
                  f"E0={best['E0_gev']:.4f}({best['E0_gev_sdev']:.4f}) GeV, "
                  f"χ²/dof={best['chi2_per_dof']:.2f}, Q={best['Q']:.3f}")
            print(f"  Robust:       [{robust['tmin']},{robust['tmax']}) "
                  f"χ²/dof={robust['chi2_per_dof']:.2f}, Q={robust['Q']:.3f}")
        else:
            print(f"  All {len(fit_result.get('all_results',[]))} windows failed.")
            print(f"  Falling back to meff plateau estimate.")

        all_fit_results[Pz] = fit_result

        # Save
        fit_save = {k: v for k, v in fit_result.items() if k != "all_results"}
        if "all_results" in fit_result:
            fit_save["all_results"] = [
                {kk: vv for kk, vv in r.items() if kk != "fit_object"}
                for r in fit_result["all_results"]
            ]
        with open(f"{args.output_dir}/fit_results_Pz{Pz}.json", "w") as f:
            json.dump(fit_save, f, indent=2, default=str)

        # Plot
        plot_meff_with_fit(C_1d, fit_result, Pz, args.output_dir, args.conf_id)

    # ── E0 dispersion ──
    plot_e0_dispersion(all_fit_results,
                        f"{args.output_dir}/e0_dispersion_conf{args.conf_id}.pdf")

    # ── Summary table ──
    t_end = time.perf_counter()
    print(f"\n{'═'*60}")
    print(f"  lamet-agent Analysis Complete — {t_end-t_start:.1f}s")
    print(f"{'═'*60}")
    print(f"  {'Pz':>4s}  {'E0 [GeV]':>14s}  {'χ²/dof':>8s}  {'Q':>8s}  {'Window':>12s}")
    print(f"  {'─'*56}")
    for Pz in sorted(all_fit_results.keys()):
        r = all_fit_results[Pz]
        best = r.get("best_window", {})
        if best.get("status") == "ok":
            print(f"  {Pz:4d}  {best['E0_gev']:14.6f}  "
                  f"{best['chi2_per_dof']:8.3f}  {best['Q']:8.4f}  "
                  f"[{best['tmin']},{best['tmax']})")
    print(f"{'═'*60}")


def _fallback_meff_only(args):
    """Fallback: compute and plot effective mass without lsqfit."""
    Pz_list = [int(p) for p in args.Pz_list.split(",")]
    os.makedirs(args.output_dir, exist_ok=True)

    for Pz in Pz_list:
        try:
            C_1d = load_2pt_data(args.data_dir, Pz, args.conf_id)
        except FileNotFoundError as e:
            print(f"[SKIP] {e}")
            continue

        C_pos = np.abs(C_1d) + 1e-30
        cosh_arg = (C_pos[2:] + C_pos[:-2]) / (2.0 * C_pos[1:-1])
        valid = cosh_arg >= 1.0
        meff_lu = np.full(Nt - 2, np.nan)
        meff_lu[valid] = np.arccosh(cosh_arg[valid])
        meff_gev = meff_lu * fm2GeV / alttc_fm

        ps, pe = Nt // 4, Nt // 2
        plateau = meff_gev[ps:pe][~np.isnan(meff_gev[ps:pe])]
        plateau_mean = np.mean(plateau) if len(plateau) > 0 else np.nan

        print(f"Pz={Pz:4d}: plateau ({ps}-{pe}) meff = {plateau_mean:.4f} GeV")

        np.savez(f"{args.output_dir}/meff_fallback_Pz{Pz}_conf{args.conf_id}.npz",
                  meff_gev=meff_gev, C_1d=C_1d, plateau_mean=plateau_mean)


if __name__ == "__main__":
    main()
